version: '3'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/postgres/data:/var/lib/mysql
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
